routes/web.php
<?php

use App\Http\Controllers\PrincipalController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/'); 

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria'); 

Route::get('procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes'); 

Route::get('conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes'); 

Route::get('/principal', [PrincipalController::class, 'principal']); 
   
Route::get('/pagina1', [PrincipalController::class, 'pagina1']) ;

Route::get('/pagina2',  [PrincipalController::class, 'pagina2']) ;

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;
    public function getResistenciaInternaAttribute(){
        return $this->resistencia_carga * ($this->tensao_sem_carga / $this->tensao_com_carga - 1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Medicoes;
use Illuminate\Http\Request;

class PrincipalController extends Controller
{
    public function principalBaterias() {
        return view('principalBaterias');
    }
    public function teoria() {
        return view('teoria');
    }
    public function procedimento() {
        return view('procedimento');
    }
    public function medicoes() {
        $medicoes = Medicoes :: all();
        return view('medicoes',compact('medicoes'));
    }
    public function conclusoes() {
        return view('conclusoes');
    }

    public function principal() {
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }
    public function pagina2() {
        return view('pagina2');
    }
 }

resources/views/conclusoes.blade.php
@extends ('templates.base')

@section ('conteudo')
    <main>
        <h1>CONCLUSÕES</h1>
        <hr>
       
        <p>
        A conclusão feita, foi que, "a vida útil" de cada pilha ou bateria está associado com a tensão com carga relativamente à tensão nominal, assim como, o valor da respectiva resistência interna.
        Com tudo, aprendemos a calcular a resistência interna de uma pilha/bateria, utilizando dados calculados por um multímetro e associando às determiadas tensões de cada um. 
        Para o desenvolvimento do trabalho, tivemos que aplicar conhecimentos relacionados à HTML para a criação do site, em Eletroeletrônica para as análises no Multímetro e os cálculos realizados para saber resistência, tensão e etc...<br>
        À partir de um trabalho sobre baterias em geral, cada mebro em específico teve uma função condizente com sua preferência. Tais como, André, que manteve a parte de javascript atualizada corretamente, e que inclusive foi o “owner” de todo o projeto, nos guiando dentre todos os tipos de códigos que precisamos utilizar.
Diogo, que foi o principal desenvolvedor do código html, se manteve centrado em fazer tudo que o codigo necessitava, contando também com a ajuda de todos os membros.
Walmir, que participou principalmente das medições que envolviam os 10 tipos de bateria/pilha.
E por último, mas não menos importante, o Luiz, que participou da criação do código em css, fazendo o nosso código principal ter uma organização necessária.


        </p>
    </main>
@endsection

@section('rodape')
<h4>Rodape conclusoes</h4>
@endsection

resources/views/medicoes.blade.php
@extends ('templates.base')

@section ('conteudo')
    <main>
        <h1>Medições</h1>
        <hr>
        <h2>Valores obtidos:</h2>
        <table class="table table-stiped  table-bordered" id="tbDados">
            <thead>
            <tr>
                <th> Bateria </th>
                <th> Tensão nominal </th>
                <th> Capacidade de corrente </th>
                <th> Tensão sem carga </th>
                <th> Tensão com carga </th>
                <th> Resistência de carga "OHM"</th>
                <th> Resistência interna "OHM"</th>
        
            </tr>
            </thead>
            <tbody>
                @foreach ($medicoes as $medicao)
                    
               
                <tr>
                    <td>  { {$medicao->pilha_bateria}}</td>
                    <td> {{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                    <td> {{$medicao->capacidade_corrente}}</td>
                    <td> {{$medicao->tensao_sem_carga}}</td>
                    <td>{{$medicao->tensao_com_carga}}</td>
                    <td> {{$medicao->resistencia_carga}}</td>
                    <td> {{number_format($medicao->resistencia_interna,3,'.','')}}</td>
                </tr>
                @endforeach
            </tbody>
 
        </table>
    </main>
    @endsection

@section('rodape')
<h4>Rodape </h4>
@endsection

resources/views/pagina1.blade.php
@extends ('templates.base')

@section ('conteudo')
<h2>Pagina Principal</h2>
<hr>
@endsection

@section('rodape')
<h4>Rodape da pagina 1</h4>
@endsection

resources/views/pagina2.blade.php
@extends ('templates.base')

@section ('conteudo')
<h2>Pagina Principal</h2>
<hr>
@endsection

@section('rodape')
<h4>Rodape da pagina 2</h4>
@endsection

resources/views/principal.blade.php
@extends ('templates.base')

@section ('conteudo')
<h2>Pagina Principal</h2>
<hr>
@endsection

@section('rodape')
<h4>Rodape da pagina principal</h4>
@endsection

resources/views/principalBaterias.blade.php
@extends('templates.base')

@section('conteudo')
    

  <main>
    <h1>Turma: 2D1 - Grupo 2</h1>
    <h2>Professor:Ronaldo Silva Trindade</h2>
    <h3>Participantes:</h3>
    
    <hr>
 
  <table class="table table-striped">
    
    <tr>
        <td> MATRICULA </td>
        <td> NOME </td>
        <td> FUNÇÃO </td>
        
    </tr>
    <tr>
        <td> 0073411 </td>
        <td> Diogo Morais</td>
        <td> Desenvolvedor de HTML/CSS</td>
        
    </tr>
    <tr>
        <td> 0072553</td>
        <td> Walmir de Jesus</td>
        <td> Medições</td>
        
    </tr>
    <tr>
        <td> 0065648</td>
        <td> Andre Vieira</td>
        <td>  Gerente</td>
        
    </tr>
    <tr>
        <td> 0073608</td>
        <td> Luiz Felipe</td>
        <td> Desenvolvedor de JS</td>
        
    </tr>
    
    <img src="../trabeletro/pics/Baterias/IMG_0726.PNG" class="grupo">
    
  </table>
</main>
@endsection

@section('rodape')
<h4>Rodapé da página principal</h4>
@endsection

resources/views/procedimento.blade.php
@extends ('templates.base')

@section ('conteudo')
    <main>
        <h1>Procedimento</h1>
        <hr>
        <h2>Medições:</h2>
        <p>
            1° passo : Separação dos materiais: multímetro, baterias e pilhas.<br>
            2° passo : Com o multímetro, foi feita a medição da tensão interna (E) e da tensão com carga (V) das pilhas e das baterias que foram apresentadas no laboratório.<br>
            3° passo : Calculamos o valor real do resistor (R), utilizado como carga.<br>
            4° passo: Após as medições, anotamos o valor de cada pilha e cada bateria (totalizando 10) para determinar a resistência interna (r) e suas "vida útil".<br>
            5° passo : Para saber a vida útil das pilhas/baterias, foi necessários medirmos a tensão, juntamente com a resistência interna.<br>

        </p>
    </main>
@endsection

@section('rodape')
    <h4>Rodape procedimentos</h4>
@endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AulaLaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/estilos.css') }}">
    <style>
    body {
        background-color: rgb(173, 216 ,230);
    }
    </style>
</head>

<body>
    <div class="container -md">
    <h1>Baterias Laravel</h1>
    <hr>
    <nav>
        <ul>
            <li><a href="{{ route('/') }}">Inicio</a></li>
            <li><a href="{{ route('teoria') }}">Teoria</a></li>
            <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
            <li><a href="{{ route('medicoes') }}">Medicoes</a></li>
            <li><a href="{{ route('conclusoes') }}">Conclusoes</a></li>
        </ul>
    </nav>
    @yield ("conteudo")
    <div class="rodape container -md">
        @yield ("rodape")
    </div>
   
   </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

resources/views/teoria.blade.php
@extends ('templates.base')

@section ('conteudo')

    <main>
        <h1>Teoria</h1>
        <hr>
        <h2>Descrição das pilhas:</h2>
        <p>  
            As baterias recarregáveis ​​são dispositivos eletroquímicos que podem ser carregados e descarregados várias vezes, permitindo o uso prolongado em comparação com as baterias descartáveis. Essas baterias são uma opção mais econômica e sustentável, pois atendem a necessidade de substituição frequente e descarte de baterias usadas. <br>
            <br>
            <img src="../pics/Baterias/energy elgin.jpg" > <br>
            <br>
            <br>
            Uma pilha recarregável, também conhecida como bateria recarregável, é um dispositivo que pode ser recarregado após o esgotamento de sua carga. Ao contrário das pilhas descartáveis ​​tradicionais, as pilhas recarregáveis ​​​​são projetadas para serem usadas repetidamente, o que as torna uma opção mais econômica e ambientalmente amigável a longo prazo. <br>
            <br>
            <img src="../pics/Baterias/J.Y.X.jpg" >  <br>
              <br>
            Uma pilha não recarregável, também conhecida como pilha descartável ou pilha primária, é um dispositivo eletroquímico que produz energia por meio de uma reação química e não pode ser recarregada. Elas são projetadas para serem usadas uma única vez e, quando a energia é esgotada, devem ser descartadas como prioritárias.<br>
            
As pilhas não recarregáveis ​​são comumente encontradas em diferentes tamanhos e formatos, como pilhas alcalinas (AA, AAA, C, D, etc.) e pilhas de zinco-carbono. Elas são amplamente utilizadas em dispositivos eletrônicos de uso cotidiano, como controles remotos, lanternas, brinquedos, relógios, entre outros <br>
<br>
            <img src="../pics/Baterias/duracell AA.jpg" width="300px" > <br>
            <br>
            
            
            As baterias não recarregáveis, também conhecidas como baterias descartáveis, são projetadas para fornecer energia por um determinado período de tempo e, uma vez esgotadas, não podem ser recarregadas novamente. Elas são geralmente compostas por materiais químicos que reagem para gerar eletricidade, mas essa reação é irreversível, o que significa que a bateria não pode ser recarregada.
Existem diferentes tipos de baterias não recarregáveis, cada uma com suas próprias características e aplicações. <br>
            <img src="../pics/Baterias/golite.jpg" >  <br>
        </p>
    </main>
    @endsection

    @section('rodape')
    <h4>Rodape teoria</h4>
    @endsection